name: Werewolf
version: 1.5.3
api-version: 1.13
main: us.rfsmassacre.Werewolf.WerewolfPlugin
author: RFSMassacre
softdepend: [SkinsRestorer, Vampire, VampireRevamp, MCore, MassiveCore, Multiverse-Core]
commands:
  werewolf:
    usage: /ww
    permission: werewolf.werewolf
    aliases: ww
    default: true
  werewolfadmin:
    usage: /wwa
    permission: werewolfadmin.werewolf
    aliases: wwa
    default: false